export interface DataSource {
  id: string
  name: string
  shortName: string
  type: 'api' | 'download' | 'derived'
  url: string
  metrics: string[]
  updateFrequency: 'monthly' | 'quarterly' | 'annual'
  geographyLevels: string[]
  requiresApiKey: boolean
  apiKeyEnvVar?: string
  notes: string
  fallback?: string
}

export const DATA_SOURCES: DataSource[] = [
  {
    id: 'census_acs',
    name: 'U.S. Census Bureau — American Community Survey',
    shortName: 'Census ACS',
    type: 'api',
    url: 'https://api.census.gov/data/2022/acs/acs5',
    metrics: ['population', 'net_migration', 'median_household_income', 'housing_characteristics'],
    updateFrequency: 'annual',
    geographyLevels: ['nation', 'state', 'county', 'metro'],
    requiresApiKey: true,
    apiKeyEnvVar: 'CENSUS_API_KEY',
    notes: '1-year lag. Gold standard for demographic data. Register at api.census.gov/data/key_signup.html',
    fallback: 'census_population_estimates',
  },
  {
    id: 'census_pop_estimates',
    name: 'U.S. Census Bureau — Population Estimates Program',
    shortName: 'Census PEP',
    type: 'api',
    url: 'https://api.census.gov/data/2023/pep/population',
    metrics: ['population', 'population_growth'],
    updateFrequency: 'annual',
    geographyLevels: ['nation', 'state', 'county', 'metro'],
    requiresApiKey: true,
    apiKeyEnvVar: 'CENSUS_API_KEY',
    notes: 'More current than ACS. Published July each year for prior year.',
  },
  {
    id: 'bls_laus',
    name: 'Bureau of Labor Statistics — LAUS',
    shortName: 'BLS LAUS',
    type: 'api',
    url: 'https://api.bls.gov/publicAPI/v2/timeseries/data/',
    metrics: ['unemployment_rate', 'labor_force'],
    updateFrequency: 'monthly',
    geographyLevels: ['nation', 'state', 'metro', 'county'],
    requiresApiKey: true,
    apiKeyEnvVar: 'BLS_API_KEY',
    notes: 'Free tier: 500 series/day. With key: 2,500/day. Monthly, published 3-4 weeks after period.',
  },
  {
    id: 'bls_qcew',
    name: 'Bureau of Labor Statistics — QCEW',
    shortName: 'BLS QCEW',
    type: 'download',
    url: 'https://www.bls.gov/cew/downloadable-data-files.htm',
    metrics: ['job_growth', 'wages', 'employment_by_sector'],
    updateFrequency: 'quarterly',
    geographyLevels: ['nation', 'state', 'county', 'metro'],
    requiresApiKey: false,
    notes: '~6 month lag. County-level job data. Download quarterly CSV files.',
  },
  {
    id: 'bea_regional',
    name: 'Bureau of Economic Analysis — Regional',
    shortName: 'BEA',
    type: 'api',
    url: 'https://apps.bea.gov/api/data',
    metrics: ['gdp', 'personal_income'],
    updateFrequency: 'annual',
    geographyLevels: ['nation', 'state', 'metro'],
    requiresApiKey: true,
    apiKeyEnvVar: 'BEA_API_KEY',
    notes: '~6 month lag for metro GDP. State GDP more current. Free API key at apps.bea.gov/api/signup',
  },
  {
    id: 'redfin',
    name: 'Redfin Data Center',
    shortName: 'Redfin',
    type: 'download',
    url: 'https://www.redfin.com/news/data-center/',
    metrics: ['median_list_price', 'days_on_market', 'active_inventory', 'new_listings', 'price_reductions'],
    updateFrequency: 'monthly',
    geographyLevels: ['nation', 'state', 'metro', 'county', 'zip'],
    requiresApiKey: false,
    notes: 'Free CSV downloads. Best source for housing market data. Check terms of service for commercial use.',
    fallback: 'fhfa_hpi',
  },
  {
    id: 'fhfa_hpi',
    name: 'FHFA House Price Index',
    shortName: 'FHFA HPI',
    type: 'download',
    url: 'https://www.fhfa.gov/data/hpi',
    metrics: ['home_price_index', 'home_price_appreciation'],
    updateFrequency: 'quarterly',
    geographyLevels: ['nation', 'state', 'metro'],
    requiresApiKey: false,
    notes: 'Free download. Quarterly for metro/state, monthly for national. Best trend data for prices.',
  },
  {
    id: 'hud_fmr',
    name: 'HUD Fair Market Rents',
    shortName: 'HUD FMR',
    type: 'download',
    url: 'https://www.huduser.gov/portal/datasets/fmr.html',
    metrics: ['fair_market_rent', 'rent_by_bedroom'],
    updateFrequency: 'annual',
    geographyLevels: ['county', 'metro'],
    requiresApiKey: false,
    notes: 'Annual FY release. County-level. Use as affordability baseline for rent.',
  },
  {
    id: 'zillow_zori',
    name: 'Zillow Observed Rent Index',
    shortName: 'ZORI',
    type: 'download',
    url: 'https://www.zillow.com/research/data/',
    metrics: ['rent_index', 'rent_growth'],
    updateFrequency: 'monthly',
    geographyLevels: ['nation', 'state', 'metro', 'county', 'zip'],
    requiresApiKey: false,
    notes: 'Free download. Monthly metro-level rent data. Check terms of service.',
    fallback: 'hud_fmr',
  },
  {
    id: 'census_permits',
    name: 'Census Building Permits Survey',
    shortName: 'Census BPS',
    type: 'api',
    url: 'https://www.census.gov/construction/bps/',
    metrics: ['building_permits', 'housing_starts'],
    updateFrequency: 'monthly',
    geographyLevels: ['nation', 'state', 'metro', 'county'],
    requiresApiKey: true,
    apiKeyEnvVar: 'CENSUS_API_KEY',
    notes: 'Monthly permit data at county level. Good construction pipeline indicator.',
  },
  {
    id: 'fred',
    name: 'FRED — St. Louis Fed',
    shortName: 'FRED',
    type: 'api',
    url: 'https://fred.stlouisfed.org/docs/api/fred/',
    metrics: ['mortgage_rates', 'housing_starts', 'vacancy_rate', 'various'],
    updateFrequency: 'monthly',
    geographyLevels: ['nation', 'state'],
    requiresApiKey: true,
    apiKeyEnvVar: 'FRED_API_KEY',
    notes: 'Free API key at fred.stlouisfed.org. Mostly national/state. 120 req/10min limit.',
  },
]
