import type { MetricKey } from '@/types/metrics'

export interface MetricDefinition {
  key: MetricKey
  label: string
  shortLabel: string
  description: string
  unit: 'currency' | 'days' | 'percent' | 'number' | 'ratio'
  format: string
  source: string
  updateFrequency: 'monthly' | 'quarterly' | 'annual'
  higherIsBetter: boolean
  category: 'housing' | 'migration' | 'economic' | 'affordability'
}

export const METRIC_DEFINITIONS: Record<MetricKey, MetricDefinition> = {
  median_list_price: {
    key: 'median_list_price',
    label: 'Median List Price',
    shortLabel: 'List Price',
    description: 'Median listing price for active residential listings',
    unit: 'currency',
    format: '$0.0a',
    source: 'Redfin Data Center',
    updateFrequency: 'monthly',
    higherIsBetter: false,
    category: 'housing',
  },
  days_on_market: {
    key: 'days_on_market',
    label: 'Days on Market',
    shortLabel: 'DOM',
    description: 'Median number of days listings sit before going under contract',
    unit: 'days',
    format: '0',
    source: 'Redfin Data Center',
    updateFrequency: 'monthly',
    higherIsBetter: false,
    category: 'housing',
  },
  active_inventory: {
    key: 'active_inventory',
    label: 'Active Inventory',
    shortLabel: 'Inventory',
    description: 'Number of active residential listings',
    unit: 'number',
    format: '0,0',
    source: 'Redfin Data Center',
    updateFrequency: 'monthly',
    higherIsBetter: false,
    category: 'housing',
  },
  price_reductions_pct: {
    key: 'price_reductions_pct',
    label: 'Price Reductions',
    shortLabel: 'Price Cuts',
    description: '% of listings with at least one price reduction',
    unit: 'percent',
    format: '0.0%',
    source: 'Redfin Data Center',
    updateFrequency: 'monthly',
    higherIsBetter: false,
    category: 'housing',
  },
  months_of_supply: {
    key: 'months_of_supply',
    label: 'Months of Supply',
    shortLabel: 'Mo. Supply',
    description: 'How many months to sell current inventory at current sales pace',
    unit: 'number',
    format: '0.0',
    source: 'Redfin / Derived',
    updateFrequency: 'monthly',
    higherIsBetter: false,
    category: 'housing',
  },
  net_migration_rate: {
    key: 'net_migration_rate',
    label: 'Net Migration Rate',
    shortLabel: 'Migration',
    description: 'Net migration per 1,000 residents annually',
    unit: 'ratio',
    format: '+0.0',
    source: 'U.S. Census ACS',
    updateFrequency: 'annual',
    higherIsBetter: true,
    category: 'migration',
  },
  unemployment_rate: {
    key: 'unemployment_rate',
    label: 'Unemployment Rate',
    shortLabel: 'Unemployment',
    description: 'Seasonally adjusted unemployment rate',
    unit: 'percent',
    format: '0.0%',
    source: 'BLS LAUS',
    updateFrequency: 'monthly',
    higherIsBetter: false,
    category: 'economic',
  },
  job_growth_pct: {
    key: 'job_growth_pct',
    label: 'Job Growth',
    shortLabel: 'Jobs',
    description: 'Year-over-year total nonfarm job growth',
    unit: 'percent',
    format: '+0.0%',
    source: 'BLS QCEW',
    updateFrequency: 'quarterly',
    higherIsBetter: true,
    category: 'economic',
  },
  gdp_growth_pct: {
    key: 'gdp_growth_pct',
    label: 'GDP Growth',
    shortLabel: 'GDP',
    description: 'Real GDP growth rate',
    unit: 'percent',
    format: '+0.0%',
    source: 'BEA Regional',
    updateFrequency: 'annual',
    higherIsBetter: true,
    category: 'economic',
  },
  median_household_income: {
    key: 'median_household_income',
    label: 'Median Household Income',
    shortLabel: 'Income',
    description: 'Median annual household income',
    unit: 'currency',
    format: '$0,0',
    source: 'U.S. Census ACS',
    updateFrequency: 'annual',
    higherIsBetter: true,
    category: 'economic',
  },
  population_growth_pct: {
    key: 'population_growth_pct',
    label: 'Population Growth',
    shortLabel: 'Pop. Growth',
    description: 'Year-over-year population growth rate',
    unit: 'percent',
    format: '+0.0%',
    source: 'U.S. Census Estimates',
    updateFrequency: 'annual',
    higherIsBetter: true,
    category: 'migration',
  },
  rent_growth_yoy_pct: {
    key: 'rent_growth_yoy_pct',
    label: 'Rent Growth',
    shortLabel: 'Rent Growth',
    description: 'Year-over-year rent appreciation',
    unit: 'percent',
    format: '+0.0%',
    source: 'Zillow ZORI / HUD FMR',
    updateFrequency: 'monthly',
    higherIsBetter: false,
    category: 'affordability',
  },
  price_to_income_ratio: {
    key: 'price_to_income_ratio',
    label: 'Price-to-Income Ratio',
    shortLabel: 'P/I Ratio',
    description: 'Median home price divided by median annual household income',
    unit: 'ratio',
    format: '0.0x',
    source: 'Derived (Redfin + Census)',
    updateFrequency: 'monthly',
    higherIsBetter: false,
    category: 'affordability',
  },
  affordability_index: {
    key: 'affordability_index',
    label: 'Affordability Score',
    shortLabel: 'Affordability',
    description: 'Composite affordability index (0-100, higher = more affordable)',
    unit: 'number',
    format: '0',
    source: 'Watchtower Derived',
    updateFrequency: 'monthly',
    higherIsBetter: true,
    category: 'affordability',
  },
}

export const MAP_LAYERS: { key: MetricKey; label: string; colorScheme: string }[] = [
  { key: 'median_list_price', label: 'Median List Price', colorScheme: 'reds' },
  { key: 'days_on_market', label: 'Days on Market', colorScheme: 'oranges' },
  { key: 'price_reductions_pct', label: 'Price Reductions %', colorScheme: 'purples' },
  { key: 'months_of_supply', label: 'Months of Supply', colorScheme: 'blues' },
  { key: 'net_migration_rate', label: 'Net Migration Rate', colorScheme: 'greens' },
  { key: 'unemployment_rate', label: 'Unemployment Rate', colorScheme: 'reds' },
  { key: 'job_growth_pct', label: 'Job Growth %', colorScheme: 'greens' },
  { key: 'population_growth_pct', label: 'Population Growth', colorScheme: 'blues' },
  { key: 'affordability_index', label: 'Affordability', colorScheme: 'greens' },
  { key: 'price_to_income_ratio', label: 'Price/Income Ratio', colorScheme: 'reds' },
]
